### PR TITLE
Fix importer issues

### LINKED ISSUE #90: Importer window issues
- [x] set minWidth to the importer window.
- [x] make file icon visible when the row is selected.
- [x] add padding 
Image
- [x] vertically align change button at the center.
- [x] closing the window should have the same logic as the cancel button.
- [x] when "Import" has being pressed before "Import project", the path is not dropped.
- [x] generalize the file names in the alert

### PR DESCRIPTION
**Pull request by Anastasia-Nikitina**

### CODE REVIEW

File: src/main/kotlin/solve/importer/ProjectParser.kt [hunk 1]
```diff
@@ -46,23 +45,23 @@ object ProjectParser {
...
-                    } algorithm for image ${frame.frame.timestamp}"
-                )
+                addNoSomeAlgorithmErrorMessage("is", "")
             } else {
-                frame.errorMessage.add(
-                    "There are no ${
-                        diffString.toMutableList().toStringWithoutBrackets()
-                    } algorithms for image ${frame.frame.timestamp}"
-                )
+                addNoSomeAlgorithmErrorMessage("are", "s")
```
Comment (DmiitriyJarosh) [inline src/main/kotlin/solve/importer/ProjectParser.kt]: decide inside special func by logic, not hardcode here))

**Review by DmiitriyJarosh — CHANGES_REQUESTED** [review]

File: src/main/kotlin/solve/importer/ProjectParser.kt (hunk 1 above)
Comment (Anastasia-Nikitina) [reply src/main/kotlin/solve/importer/ProjectParser.kt]: so, to put this `if` into a function `addNoSomeAlgorithmErrorMessage`?

Comment (Anastasia-Nikitina) [reply src/main/kotlin/solve/importer/ProjectParser.kt]: I tried to avoid code duplication. And if you take out `if`, then it will be inside the function

Comment (DmiitriyJarosh) [reply src/main/kotlin/solve/importer/ProjectParser.kt]: yes, you can put if in such way that only different code is in it, while the same one is not duplicated)

File: src/main/kotlin/solve/importer/ProjectParser.kt [hunk 2]
```diff
@@ -45,25 +47,23 @@ object ProjectParser {
...
         }.toSet())
         val diffString = diff.map { layer ->
-            layer.name + "_" + layer.kind
+            layer.name
         }
 
-        if (diff.isNotEmpty()) {
-            frame.isImageErrored = true
+        fun addNoSomeAlgorithmErrorMessage() {
+            val missingAlgorithms = diffString.toMutableList().toStringWithoutBrackets()
```
Comment (DmiitriyJarosh) [inline src/main/kotlin/solve/importer/ProjectParser.kt:54]: why do we need mutable List?

File: src/main/kotlin/solve/importer/ProjectParser.kt [hunk 3]
```diff
@@ -45,25 +47,23 @@ object ProjectParser {
...
+            val imageTimestamp = frame.importerFrame.timestamp
             if (diff.count() == 1) {
-                frame.errorMessage.add(
-                    "There is no ${
-                        diffString.toMutableList().toStringWithoutBrackets()
-                    } algorithm for image ${frame.importerFrame.timestamp}"
-                )
+                frame.errorMessage.add("There is no $missingAlgorithms algorithm for image $imageTimestamp")
```
Comment (DmiitriyJarosh) [inline src/main/kotlin/solve/importer/ProjectParser.kt]: commented in discord

**Review by DmiitriyJarosh — CHANGES_REQUESTED** [review]

File: src/main/kotlin/solve/importer/ProjectParser.kt (hunk 2 above)
Comment (Anastasia-Nikitina) [reply src/main/kotlin/solve/importer/ProjectParser.kt:54]: because `toStringWithoutBrackets`` takes mutable List. In most cases, it is  used and I decided not to write another function for a immutable List.

**Review by DmiitriyJarosh — APPROVED** [review]
