### PR TITLE
Bug fix in importer

### LINKED ISSUE #83: Importer bugs
1. Problem with reimport
2. Exception is if you do not select a directory, but close the file system window
3. Button  "Change" is located on the left, and when you select a directory, it moves to the right
4. Even if the directory is already selected, the file system window opens in the root directory

### PR DESCRIPTION
**Pull request by Anastasia-Nikitina**

### CODE REVIEW

File: src/main/kotlin/sliv/tool/importer/view/ChoosingDirectoryView.kt [hunk 1]
```diff
@@ -19,45 +20,71 @@ class ChoosingDirectoryView : Fragment() {
...
+                    button("Import") {
+                        prefWidth = 180.0
+                        isDisable = true
+                        project.onChange {
+                            if (project.value.frames.isNotEmpty()) {
+                                isDisable = false
+                            }
+                        }
+                        action {
+                            val projectVal = project.value
```
Comment (DmiitriyJarosh) [inline src/main/kotlin/sliv/tool/importer/view/ChoosingDirectoryView.kt]: you use already parsed project here, but what if it will have 1 million files? when will slow moment be?

**Review by DmiitriyJarosh — CHANGES_REQUESTED** [review]

**Review by DmiitriyJarosh — APPROVED** [review]
