### PR TITLE
Fix scene memory leaks

### LINKED ISSUE #107: Memory leak when recreating grid cells
To reproduce the issue pass data from the catalogue into the scene multiple times

### PR DESCRIPTION
**Pull request by Alexander-Ploskin**

### CODE REVIEW

File: src/main/kotlin/solve/scene/view/SceneView.kt [hunk 1]
```diff
@@ -32,6 +33,8 @@ class SceneView : View() {
     }
 
     private fun draw() {
+        System.gc()
```
Comment (DmiitriyJarosh) [inline src/main/kotlin/solve/scene/view/SceneView.kt]: why we need to call collector?

Comment (Alexander-Ploskin) [reply src/main/kotlin/solve/scene/view/SceneView.kt]: Removed

**Review by DmiitriyJarosh — APPROVED** [review]
